[mgr]
prepend_keymap = [
  { on = "<enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "o", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "-", run = "leave", desc = "Leave the current directory and enter parent" },
]
