# allows nvim colors
set-option -ga terminal-overrides ",xterm-256color:Tc"  

# makes ESC more responsive
set-option -g escape-time 10  

set -g mouse on

bind-key q kill-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind V split-window -h
bind H split-window -v

# opens a new pane in the current working directory
bind p new-window -c "#{pane_current_path}"

set -g status-bg "#d08770"
